
### Create a new user
POST https://extreme-ivonne-gedeontiga-3cf88bd1.koyeb.app/api/auth/register
Content-Type: application/json

{
    "firstName": "Gedeon",
    "lastName": "Test",
    "email": "gedeontigadev@gmail.com",
    "password": "test....",
    "address": "123 Main Street, City",
    "phoneNumber": "+1234567890"
}


### Activate user
GET https://extreme-ivonne-gedeontiga-3cf88bd1.koyeb.app/activate?token=828c5824-5c8d-4b52-90e0-a3e29a0f0ad5

### Login
POST https://extreme-ivonne-gedeontiga-3cf88bd1.koyeb.app/api/auth/login
Content-Type: application/json

{
    "email": "gedeontigadev@gmail.com",
    "password": "test...."
}